package constant

//HealthRecordServiceType ...
type HealthRecordServiceType string

const (
	//OrganizationService ...
	OrganizationService HealthRecordServiceType = "organizationService"

	//PractitionerService ...
	PractitionerService HealthRecordServiceType = "practitionerService"

	//ConsumerService ...
	ConsumerService HealthRecordServiceType = "consumerService"

	//HeartRateService ...
	HeartRateService HealthRecordServiceType = "heartRateService"

	//ClinicalCodeService ...
	ClinicalCodeService HealthRecordServiceType = "clinicalCodeService"

	//ClinicalCodeSystemService ...
	ClinicalCodeSystemService HealthRecordServiceType = "clinicalCodeSystemService"

	//DosageService ...
	DosageService HealthRecordServiceType = "dosageService"

	//StrengthService ...
	StrengthService HealthRecordServiceType = "strengthService"

	//MedicationService ...
	MedicationService HealthRecordServiceType = "medicationService"

	//ContactPointService ...
	ContactPointService HealthRecordServiceType = "contactPointService"

	//HealthRecordService ...
	HealthRecordService HealthRecordServiceType = "healthRecordService"

	//SourceRecordIDService ...
	SourceRecordIDService HealthRecordServiceType = "sourceRecordIDService"

	//SourceConsumerIDService ...
	SourceConsumerIDService HealthRecordServiceType = "sourceConsumerIDService"

	//SourceOrganizationIDService ...
	SourceOrganizationIDService HealthRecordServiceType = "sourceOrganizationIDService"

	//AccountService ...
	AccountService HealthRecordServiceType = "accountService"

	//SocialHistoryObservationRecordService ...
	SocialHistoryObservationRecordService HealthRecordServiceType = "socialHistoryObservationRecordService"

	//MedicationRecordService ...
	MedicationRecordService HealthRecordServiceType = "medicationRecordService"

	//AllergyRecordService ...
	AllergyRecordService HealthRecordServiceType = "allergyRecordService"

	//EncounterRecordService ...
	EncounterRecordService HealthRecordServiceType = "encounterRecordService"

	//AddressService ...
	AddressService HealthRecordServiceType = "addressService"

	//FamilyMemberHistoryRecordService ...
	FamilyMemberHistoryRecordService HealthRecordServiceType = "familyMemberHistoryRecordService"

	//ProcedureRecordService ...
	ProcedureRecordService HealthRecordServiceType = "procedureRecordService"

	//ClinicalAssesmentObservationRecordService ...
	ClinicalAssesmentObservationRecordService HealthRecordServiceType = "clinicalAssesmentObservationRecordService"

	//PersonalCharacteristicsObservationRecordService ...
	PersonalCharacteristicsObservationRecordService HealthRecordServiceType = "personalCharacteristicsObservationRecordService"

	//ImagingResultObservationRecordService ...
	ImagingResultObservationRecordService HealthRecordServiceType = "imagingResultObservationRecordService"

	//LabResultObservationRecordService ...
	LabResultObservationRecordService HealthRecordServiceType = "labResultObservationRecordService"

	//VitalObservationRecordService ...
	VitalObservationRecordService HealthRecordServiceType = "vitalObservationRecordService"

	//ConditionRecordService ...
	ConditionRecordService HealthRecordServiceType = "conditionRecordService"

	//ImmunizationRecordService ...
	ImmunizationRecordService HealthRecordServiceType = "immunizationRecordService"

	//ActivityRecordService ...
	ActivityRecordService HealthRecordServiceType = "activityRecordService"

	//MealRecordService ...
	MealRecordService HealthRecordServiceType = "mealRecordService"

	//GoalRecordService ...
	GoalRecordService HealthRecordServiceType = "goalRecordService"

	//SleepRecordService ...
	SleepRecordService HealthRecordServiceType = "sleepRecordService"

	//AdverseEventRecordService ...
	AdverseEventRecordService HealthRecordServiceType = "adverseEventRecordService"

	//ConsentService ...
	ConsentService HealthRecordServiceType = "consentService"

	//ClinicalTrialService ...
	ClinicalTrialService HealthRecordServiceType = "clinicalTrialService"

	//ConceptClassService ...
	ConceptClassService HealthRecordServiceType = "conceptClassService"

	//CodableConceptService ...
	CodableConceptService HealthRecordServiceType = "codableConceptService"

	//QuestionnaireService ...
	QuestionnaireService HealthRecordServiceType = "questionnaireService"

	//QuestionnaireResponseService ...
	QuestionnaireResponseService HealthRecordServiceType = "questionnaireResponseService"

	//NotificationService ...
	NotificationService HealthRecordServiceType = "notificationService"

	//AcknowledgementService ...
	AcknowledgementService HealthRecordServiceType = "acknowledgementService"

	//RelationshipService ...
	RelationshipService HealthRecordServiceType = "relationshipService"

	//ProductService ...
	ProductService HealthRecordServiceType = "productService"

	//OrderService ...
	OrderService HealthRecordServiceType = "orderService"

	//OrderEventService ...
	OrderEventService HealthRecordServiceType = "orderEventService"

	//OrderBagService ...
	OrderBagService HealthRecordServiceType = "orderBagService"

	//ApplicationService ...
	ApplicationService HealthRecordServiceType = "applicationService"

	//ReferralRequestService ...
	ReferralRequestService HealthRecordServiceType = "referralRequestService"

	//AppointmentRecordService ...
	AppointmentRecordService HealthRecordServiceType = "appointmentRecordService"

	//DiagnosticReportRecordService ...
	DiagnosticReportRecordService HealthRecordServiceType = "diagnosticReportRecordService"

	//SlotService ...
	SlotService HealthRecordServiceType = "slotService"

	//ScheduleService ...
	ScheduleService HealthRecordServiceType = "scheduleService"

	//AppointmentResponseService ...
	AppointmentResponseService HealthRecordServiceType = "appointmentResponseService"

	//NutritionOrderRecordService ...
	NutritionOrderRecordService HealthRecordServiceType = "nutritionOrderRecordService"

	//DeviceService ...
	DeviceService HealthRecordServiceType = "deviceService"

	//DeviceMetricService ...
	DeviceMetricService HealthRecordServiceType = "deviceMetricService"

	//DeviceDataSourceService ...
	DeviceDataSourceService HealthRecordServiceType = "deviceDataSourceService"

	//ObservationDefinitionCollectionService ...
	ObservationDefinitionCollectionService HealthRecordServiceType = "observationDefinitionCollectionService"

	//ObservationRecordService ...
	ObservationRecordService HealthRecordServiceType = "observationRecordService"

	//MolecularSequenceRecordService ...
	MolecularSequenceRecordService HealthRecordServiceType = "molecularSequenceRecordService"

	//MessageService ...
	MessageService HealthRecordServiceType = "messageService"

	//ReviewService ..
	ReviewService HealthRecordServiceType = "reviewService"

	//DocumentReferenceService ..
	DocumentReferenceService HealthRecordServiceType = "documentReferenceService"

	//ConditionDefinitionCollectionService ...
	ConditionDefinitionCollectionService HealthRecordServiceType = "conditionDefinitionCollectionService"

	//ListService ...
	ListService HealthRecordServiceType = "listService"

	//CommentService ...
	CommentService HealthRecordServiceType = "CommentService"

	//HealthRecordExportService ...
	HealthRecordExportService HealthRecordServiceType = "healthRecordServiceType"

	//CustomerFeedbackService ...
	CustomerFeedbackService HealthRecordServiceType = "customerFeedbackService"

	//HealthcareServiceService ...
	HealthcareServiceService HealthRecordServiceType = "healthcareServiceService"
)
